name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # TODO build without doc (not needed)
    - name: Install Doxygen
      run: sudo apt-get install -y doxygen

    - name: Build & Run Unit Tests
      run: |
        git submodule update --init --recursive
        mkdir debug-build
        cd debug-build
        cmake -DBUILD_TESTS=ON -CMAKE_BUILD_TYPE=Debug ..
        make
        ctest

    - name: Build & Run examples
      run: |
        git submodule update --init --recursive
        mkdir release-build
        cd release-build
        cmake -DBUILD_TESTS=OFF -CMAKE_BUILD_TYPE=Release ..
        make
        ./paint