name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build & Run Unit Tests
      run: |
        git submodule update --init --recursive
        mkdir debug-build
        cd debug-build
        cmake -DBUILD_TESTS=ON -DBUILD_EXAMPLES=OFF -DCMAKE_BUILD_TYPE=Release ..
        make
        ctest --rerun-failed --output-on-failure

    - name: Build & Run examples
      run: |
        git submodule update --init --recursive
        mkdir release-build
        cd release-build
        cmake -DBUILD_TESTS=OFF -DBUILD_EXAMPLES=ON -DCMAKE_BUILD_TYPE=Release ..
        make
        ./paint